### ISSUE TITLE
Cannot import Burp scanner report with requests/responses

### ISSUE THREAD

**Issue by mavensecurity** [dradis/dradis-burp#2]
It seems you can only import Burp scanner reports (XML) when you omit the requests/responses.  Even with base64 encoding selected, the import (aka upload) process shows no progress/errors in Dradis.
I'm not sure if this is a known issue, a bug, or I did something wrong.  Perhaps there is something odd about the response pages for this site that prevent upload in Dradis from working properly.

**Comment by etdsoft** [comment]
The problem with the the responses (usually it isn't with the requests) is that some times they contain binary data. Burp is good at filtering images and such, but it would include in the XML things like PDFs, .ttfs. .woff files, etc.

Dealing with those binary formats is what's tripping Dradis / the Burp parser over. We can't immediately save the binary file as normal "evidence" as this is a "text" type column and the DB would complain.

We're leaning towards trying to detect binary content and displaying a warning like "[Binary Data Not Displayed]" or something along those lines.

Ideally in the future we should be able to extract this binary blob into an attachment and reference it from the Evidence.

**Comment by etdsoft** [comment]
@mavensecurity this is now implemented, we detect both non-base64 imports (and complain about them) and also base64 imports (and detect binary blobs). Shipping in the next release.

**Comment by etdsoft** [comment]
Also @mavensecurity closing the tracker of this repo, we're trying to centralise things a bit, please use dradis/dradis-ce/issues/new to follow up if needed.
